# Generated by Django 4.1.7 on 2023-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mushroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('edible', models.BooleanField()),
                ('poisonous', models.BooleanField()),
                ('area', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
